const APP_CONSTANTS = {
  GST_CAL: [
    {CATEGORY: 'FOOD', COMMODITY: ['RICE', 'WHEAT', 'DAL'], GST_PERCENTAGE: 0},
    {CATEGORY: 'FURNITURE', COMMODITY: ['TABLE', 'SOFA', 'CHAIR'], GST_PERCENTAGE: 5},
    {CATEGORY: 'ELECTRONICS', COMMODITY: ['MOBILE', 'TV', 'TABLET'], GST_PERCENTAGE: 18},
    {CATEGORY: 'COSMETICS', COMMODITY: ['CREAM', 'PERFUME', 'LOTION'], GST_PERCENTAGE: 28},
  ]
}

export default APP_CONSTANTS;
